// Self-update for an unpacked (developer-mode) extension, pulled straight
// from GitHub — no Chrome Web Store, no sync clients, no native helper app.
//
// How it works:
//   1. The repo's `update/manifest.json` (regenerated by a GitHub Action on
//      every push to main) lists the shipped files with SHA-256 hashes and
//      the current version.
//   2. The background worker polls it every few hours (chrome.alarms) and
//      stores "cuc:update-available" when a newer version exists; the widget
//      and the options page surface that.
//   3. One-time setup: on the options page the user picks the extension's
//      own folder (the one loaded at chrome://extensions) via the File
//      System Access API; the directory handle persists in IndexedDB.
//   4. "Install update" downloads every listed file, verifies each SHA-256
//      IN MEMORY first (nothing is written if anything mismatches), then
//      writes the files — manifest.json last — and the caller reloads the
//      extension via chrome.runtime.reload(), which re-reads the folder.
//
// Chrome loads unpacked extension files from disk only on (re)load, so
// overwriting them while running is safe; the reload picks them up and the
// extension ID + all chrome.storage state are preserved.
//
// Integrity model: HTTPS to GitHub/CDN + per-file SHA-256 pinned by the
// update manifest fetched over the same trust root. This protects against
// corruption and partial deploys; ultimate trust is the GitHub repo itself.
(() => {
  const UPDATE_STATE_KEY = "cuc:update-available";
  const MANIFEST_PATH = "update/manifest.json";
  const ALARM_NAME = "cuc:update-check";
  const CHECK_PERIOD_MINUTES = 6 * 60;

  // Tried in order. raw.githubusercontent.com is already host-permitted; the
  // jsDelivr CDN mirror sends CORS * and shields GitHub's per-IP rate limits
  // when many employees share one office NAT. A custom base (e.g. a
  // Cloudflare Pages deployment) can be set via settings.updateBaseUrl and
  // then takes precedence over both.
  const DEFAULT_BASES = [
    "https://raw.githubusercontent.com/zgbrenner/claudecompanion/main/",
    "https://cdn.jsdelivr.net/gh/zgbrenner/claudecompanion@main/"
  ];

  async function updateBases() {
    try {
      const stored = await chrome.storage.local.get(["cuc:settings"]);
      const custom = String(stored["cuc:settings"]?.updateBaseUrl || "").trim();
      if (custom) return [custom.endsWith("/") ? custom : `${custom}/`];
    } catch {
      // Fall through to defaults.
    }
    return DEFAULT_BASES;
  }

  function currentVersion() {
    return chrome.runtime.getManifest().version;
  }

  function compareVersions(a, b) {
    const left = String(a || "0").split(".").map(part => Number.parseInt(part, 10) || 0);
    const right = String(b || "0").split(".").map(part => Number.parseInt(part, 10) || 0);
    const length = Math.max(left.length, right.length);
    for (let i = 0; i < length; i += 1) {
      const diff = (left[i] || 0) - (right[i] || 0);
      if (diff !== 0) return diff > 0 ? 1 : -1;
    }
    return 0;
  }

  // Reject anything that could escape the extension folder or smuggle in a
  // file we don't ship. Paths must be plain relative segments under the
  // roots the extension actually uses.
  function isSafeUpdatePath(path) {
    if (typeof path !== "string" || !path) return false;
    if (!/^[A-Za-z0-9._/-]+$/.test(path)) return false;
    if (path.startsWith("/") || path.includes("..") || path.includes("//")) return false;
    return path === "manifest.json" || path.startsWith("src/") || path.startsWith("icons/");
  }

  function validUpdateManifest(manifest) {
    if (!manifest || typeof manifest !== "object") return false;
    if (typeof manifest.version !== "string" || !manifest.version) return false;
    if (!Array.isArray(manifest.files) || manifest.files.length === 0) return false;
    return manifest.files.every(file =>
      file && isSafeUpdatePath(file.path) && /^[0-9a-f]{64}$/i.test(String(file.sha256 || ""))
    );
  }

  async function fetchUpdateManifest() {
    const bases = await updateBases();
    let lastError = null;
    for (const base of bases) {
      try {
        const response = await fetch(`${base}${MANIFEST_PATH}`, { cache: "no-store" });
        if (!response.ok) throw new Error(`manifest fetch failed: ${response.status}`);
        const manifest = await response.json();
        if (!validUpdateManifest(manifest)) throw new Error("unexpected update manifest shape");
        return { manifest, base };
      } catch (error) {
        lastError = error;
      }
    }
    throw lastError || new Error("no update source reachable");
  }

  // Poll + record. Returns a summary the options page can render directly.
  async function checkForUpdate() {
    const current = currentVersion();
    const { manifest, base } = await fetchUpdateManifest();
    const updateAvailable = compareVersions(manifest.version, current) > 0;
    try {
      if (updateAvailable) {
        await chrome.storage.local.set({
          [UPDATE_STATE_KEY]: { latestVersion: manifest.version, checkedAt: Date.now() }
        });
      } else {
        await chrome.storage.local.remove([UPDATE_STATE_KEY]);
      }
    } catch {
      // Recording is best-effort; the check result is still returned.
    }
    return { currentVersion: current, latestVersion: manifest.version, updateAvailable, base };
  }

  async function getUpdateState() {
    try {
      const stored = await chrome.storage.local.get([UPDATE_STATE_KEY]);
      return stored[UPDATE_STATE_KEY] || null;
    } catch {
      return null;
    }
  }

  function scheduleUpdateChecks() {
    try {
      chrome.alarms.create(ALARM_NAME, { periodInMinutes: CHECK_PERIOD_MINUTES, delayInMinutes: 2 });
    } catch {
      // No alarms permission or API — manual checks still work.
    }
  }

  // ---- Extension-folder access (File System Access API; options page only) --

  const DB_NAME = "cuc-updater";
  const DB_STORE = "handles";
  const DB_KEY = "extension-dir";

  function openHandleDb() {
    return new Promise((resolve, reject) => {
      const request = indexedDB.open(DB_NAME, 1);
      request.onupgradeneeded = () => request.result.createObjectStore(DB_STORE);
      request.onsuccess = () => resolve(request.result);
      request.onerror = () => reject(request.error);
    });
  }

  async function saveDirectoryHandle(handle) {
    const db = await openHandleDb();
    await new Promise((resolve, reject) => {
      const tx = db.transaction(DB_STORE, "readwrite");
      tx.objectStore(DB_STORE).put(handle, DB_KEY);
      tx.oncomplete = resolve;
      tx.onerror = () => reject(tx.error);
    });
    db.close();
  }

  async function loadDirectoryHandle() {
    try {
      const db = await openHandleDb();
      const handle = await new Promise((resolve, reject) => {
        const tx = db.transaction(DB_STORE, "readonly");
        const request = tx.objectStore(DB_STORE).get(DB_KEY);
        request.onsuccess = () => resolve(request.result || null);
        request.onerror = () => reject(request.error);
      });
      db.close();
      return handle;
    } catch {
      return null;
    }
  }

  // The picked folder must actually be THIS extension's folder — check that
  // it contains a manifest.json whose name matches ours before trusting it
  // as a write target.
  async function validateExtensionFolder(handle) {
    const fileHandle = await handle.getFileHandle("manifest.json");
    const file = await fileHandle.getFile();
    const manifest = JSON.parse(await file.text());
    if (manifest?.name !== chrome.runtime.getManifest().name) {
      throw new Error("That folder doesn't contain this extension (manifest name mismatch).");
    }
  }

  async function chooseExtensionFolder() {
    if (typeof window === "undefined" || !window.showDirectoryPicker) {
      throw new Error("Folder access isn't supported in this context.");
    }
    const handle = await window.showDirectoryPicker({ mode: "readwrite" });
    await validateExtensionFolder(handle);
    await saveDirectoryHandle(handle);
    return true;
  }

  async function ensureWritableHandle({ requestIfNeeded = true } = {}) {
    const handle = await loadDirectoryHandle();
    if (!handle) return null;
    let permission = await handle.queryPermission({ mode: "readwrite" });
    if (permission === "prompt" && requestIfNeeded) {
      // Needs a user gesture — callers invoke this from a button click.
      permission = await handle.requestPermission({ mode: "readwrite" });
    }
    return permission === "granted" ? handle : null;
  }

  async function folderStatus() {
    const handle = await loadDirectoryHandle();
    if (!handle) return "unset";
    const permission = await handle.queryPermission({ mode: "readwrite" });
    return permission === "granted" ? "ready" : "needs-permission";
  }

  // ---- Applying an update ------------------------------------------------

  async function sha256Hex(buffer) {
    const digest = await crypto.subtle.digest("SHA-256", buffer);
    return Array.from(new Uint8Array(digest)).map(b => b.toString(16).padStart(2, "0")).join("");
  }

  async function writeFileToFolder(dirHandle, path, buffer) {
    const parts = path.split("/");
    const fileName = parts.pop();
    let dir = dirHandle;
    for (const part of parts) {
      dir = await dir.getDirectoryHandle(part, { create: true });
    }
    const fileHandle = await dir.getFileHandle(fileName, { create: true });
    const writable = await fileHandle.createWritable();
    await writable.write(buffer);
    await writable.close();
  }

  async function applyUpdate(onProgress = () => {}) {
    const { manifest, base } = await fetchUpdateManifest();
    const current = currentVersion();
    if (compareVersions(manifest.version, current) <= 0) {
      throw new Error(`Already up to date (v${current}).`);
    }

    const dirHandle = await ensureWritableHandle();
    if (!dirHandle) {
      const error = new Error("Extension folder not connected yet.");
      error.code = "no-folder";
      throw error;
    }
    await validateExtensionFolder(dirHandle);

    // Download and verify EVERYTHING in memory before writing a single byte,
    // so a failed download or hash mismatch can never leave a half-updated
    // (torn) folder behind.
    const downloaded = [];
    for (let i = 0; i < manifest.files.length; i += 1) {
      const { path, sha256 } = manifest.files[i];
      onProgress(`Downloading ${i + 1}/${manifest.files.length}: ${path}`);
      const response = await fetch(`${base}${path}`, { cache: "no-store" });
      if (!response.ok) throw new Error(`Download failed for ${path} (${response.status}).`);
      const buffer = await response.arrayBuffer();
      const hash = await sha256Hex(buffer);
      if (hash.toLowerCase() !== String(sha256).toLowerCase()) {
        throw new Error(`Integrity check failed for ${path} — update aborted, nothing was changed.`);
      }
      downloaded.push({ path, buffer });
    }

    // manifest.json last: it carries the version, so a crash mid-write leaves
    // the old version number in place and the updater simply retries.
    downloaded.sort((a, b) => (a.path === "manifest.json") - (b.path === "manifest.json"));
    for (let i = 0; i < downloaded.length; i += 1) {
      onProgress(`Installing ${i + 1}/${downloaded.length}: ${downloaded[i].path}`);
      await writeFileToFolder(dirHandle, downloaded[i].path, downloaded[i].buffer);
    }

    try {
      await chrome.storage.local.remove([UPDATE_STATE_KEY]);
    } catch {
      // The version inequality check hides stale banners anyway.
    }
    return { version: manifest.version };
  }

  globalThis.ClaudeUsageCompanionUpdater = {
    ALARM_NAME,
    checkForUpdate,
    getUpdateState,
    scheduleUpdateChecks,
    chooseExtensionFolder,
    folderStatus,
    applyUpdate,
    compareVersions,
    currentVersion
  };
})();
